apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dshackle.fullname" . }}
  labels:
    {{- include "dshackle.labels" . | nindent 4 }}
data:
  dshackle.yaml: |
    {{- tpl .Values.config . | nindent 4 }}
